### ISSUE TITLE
[Bug]: NoClassDefFoundError: com/sk89q/worldguard/WorldGuard

### ISSUE THREAD

**Issue by vandon1** [Wolfieheart/ArmorStandEditor#120]
### Expected behavior

Plugin should load properly

### Observed/Actual behavior

[19:47:36] [Server thread/ERROR]: Error occurred while enabling ArmorStandEditor v1.19.2-37 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldguard/WorldGuard
	at io.github.rypofalem.armorstandeditor.protections.WorldGuardProtection.<init>(WorldGuardProtection.java:42) ~[armorstandeditor-1.19.2-37.jar:?]
	at io.github.rypofalem.armorstandeditor.PlayerEditorManager.<init>(PlayerEditorManager.java:61) ~[armorstandeditor-1.19.2-37.jar:?]
	at io.github.rypofalem.armorstandeditor.ArmorStandEditorPlugin.onEnable(ArmorStandEditorPlugin.java:233) ~[armorstandeditor-1.19.2-37.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-140]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-140]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-140]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-140]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-140]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[paper-1.19.2.jar:git-Paper-140]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-140]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.WorldGuard
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]

### Steps/models to reproduce

Latest paper 1.19.2, using armorstandeditor-1.19.2-37 the plugin is disabled

### Plugin list

 Plugins (46): AnvilEnhanced, ArmorStandEditor, AureliumSkills, BlockShuffle, BungeeTabListPlus, ChestSort, DrMap, EnderDragonTweaks, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsDiscord, FireFlies, floodgate, GPFlags, Graves, GriefPrevention, GSit, harvest_xp, HolographicDisplays, IronElevators, LuckPerms, MarriageMaster, NBTAPI, NoChatReports, NotTooExpensive, OtherAnimalTeleport, PetLives, PlaceholderAPI, Playtimes, ProtectionLib, ProtocolLib, SkinsRestorer, TogglePvp, TradeShop, TreeFeller, vane-core, vane-enchantments, vane-trifles, VariableTime, Vault, ViaBackwards, ViaVersion, WorldEdit, WorldNamePacket, XPPlus

### Plugin Version

armorstandeditor-1.19.2-37

### Server Version

This server is running Paper version git-Paper-140 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: e51401e)

### Other

armorstandeditor-1.19.1-36  worked and loaded fine. Only armorstandeditor was updated

**Comment by Wolfieheart** [comment]
Thanks for reporting 1.19.2-37.2 incoming :)
