### ISSUE TITLE
[Bug]: Could not pass event PlayerInteractEvent to ArmorStandEditor v1.19.2-37.3

### ISSUE THREAD

**Issue by xOpasik** [Wolfieheart/ArmorStandEditor#127]
### Expected behavior

-

### Observed/Actual behavior

[12:33:18 ERROR]: Could not pass event PlayerInteractEvent to ArmorStandEditor v1.19.2-37.3
java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.file.YamlConfiguration.contains(String)" because "this.langConfig" is null
        at io.github.rypofalem.armorstandeditor.language.Language.getString(Language.java:132) ~[armorstandeditor-1.19.2-37.3.jar:?]
        at io.github.rypofalem.armorstandeditor.language.Language.getFormat(Language.java:126) ~[armorstandeditor-1.19.2-37.3.jar:?]
        at io.github.rypofalem.armorstandeditor.language.Language.getMessage(Language.java:76) ~[armorstandeditor-1.19.2-37.3.jar:?]
        at io.github.rypofalem.armorstandeditor.language.Language.getMessage(Language.java:88) ~[armorstandeditor-1.19.2-37.3.jar:?]
        at io.github.rypofalem.armorstandeditor.menu.Menu.<init>(Menu.java:44) ~[armorstandeditor-1.19.2-37.3.jar:?]
        at io.github.rypofalem.armorstandeditor.PlayerEditor.<init>(PlayerEditor.java:81) ~[armorstandeditor-1.19.2-37.3.jar:?]
        at io.github.rypofalem.armorstandeditor.PlayerEditorManager.addPlayerEditor(PlayerEditorManager.java:386) ~[armorstandeditor-1.19.2-37.3.jar:?]
        at io.github.rypofalem.armorstandeditor.PlayerEditorManager.getPlayerEditor(PlayerEditorManager.java:382) ~[armorstandeditor-1.19.2-37.3.jar:?]
        at io.github.rypofalem.armorstandeditor.PlayerEditorManager.onRightClickTool(PlayerEditorManager.java:323) ~[armorstandeditor-1.19.2-37.3.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[patched_1.17.1.jar:git-Purpur-1428]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:543) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:506) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:501) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:497) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:1940) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:28) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.a(ServerboundUseItemPacket.java:8) ~[app:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1450) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1428) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1421) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1399) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1310) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1428]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Steps/models to reproduce

-

### Plugin list

-

### Plugin Version

armorstandeditor-1.19.2-37.3

### Server Version

purpur 1.17.1

### Other

-

**Comment by xOpasik** [comment]
I've already fixed it, sorry for my oversight
