### ISSUE TITLE
[Bug]: Could not pass event PlayerSwapHandItemsEvent to ArmorStandEditor v1.19.4-40.2

### ISSUE THREAD

**Issue by DexterSK** [Wolfieheart/ArmorStandEditor#218]
### Expected behavior

no error/warn

### Observed/Actual behavior

[12:12:17 ERROR]: Could not pass event PlayerSwapHandItemsEvent to ArmorStandEditor v1.19.4-40.2
java.lang.NullPointerException: null
        at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
        at io.github.rypofalem.armorstandeditor.ArmorStandEditorPlugin.isEditTool(ArmorStandEditorPlugin.java:426) ~[armorstandeditor-1.19.4-40.2.jar:?]
        at io.github.rypofalem.armorstandeditor.PlayerEditorManager.onSwitchHands(PlayerEditorManager.java:208) ~[armorstandeditor-1.19.4-40.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor482.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:git-Purpur-1894]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:680) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1890) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.3.jar:git-Purpur-1894]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.3.jar:git-Purpur-1894]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.3.jar:git-Purpur-1894]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.3.jar:git-Purpur-1894]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.3.jar:git-Purpur-1894]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.3.jar:git-Purpur-1894]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.3.jar:git-Purpur-1894]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1894]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Steps/models to reproduce

idk

### Plugin list

AdvancedChests, AdvancedCoinFlip, AdvancedEnchantments, AIChat, AntiDisconnectSpam, antiRedstoneClock, AntiWorldFly, ArmorStandEditor, ArtMap, AuthMe, BattlePass, BeehivesPro, BentoBox, BestTools, Brewery, Bump, Cardinal, ChessAndMore, ChocoHills, ChristmasPlus, Chunky, Citizens, CitizensGUI, CMI, CMILib, CompressionCraft, CoreProtect, CounterStrike, CraftBook, CreativeManager, CustomArrowTrails, DecentHolograms, DeluxeMenus, DeluxeSellwands, DeluxeTags, DiscordSRV, DoorsReloaded, DragonSlayer, DyedBackpacks, DynaTech, EasyDuels, EcoPower, ElementManipulation, ElitePets, EvenMoreFish, ExcellentCrates, ExoticGarden, ExtraGear, ExtraTools, FastAsyncWorldEdit (WorldEdit), FastLogin, FlowerPower, FluffyMachines, FNAmplifications, FoxyMachines, GeneticChickengineering, GlowAPI, GrimAC, HeadDatabase, HeadLimiter, HolographicDisplays, Images, InfinityExpansion, ItemFlip, ItemsAdder, ItemsAdder-WorldEdit, Jobs, KixsChatGames, LibsDisguises, Liquid, LiteBans, LiteXpansion, LoneLibs, LuckPerms, MarriageMaster, mcMMO, MCPets, MineBlocks, MobArena, MobCoinsPlus, ModelEngine, Multiverse-Core, MythicMobs, NamelessMC, Netheopoiesis, Networks, Nexcavate, NexEngine, NoBlackSky, PacketListenerApi, PaintballBattle, Pl3xMap, PlaceholderAPI, PlayerParticles, PlayerSkills, PlayerVaults, PlayerWarps, PlugManX (PlugMan), PremiumVanish, ProtocolLib, PublicCrafters, Quests, QuickShop-Hikari, RelicsOfCthonia, ReportSystem*, Residence, SafariNet, SelectionVisualizer, ServerBooster, SFCalc, ShopGUIPlus, Shopkeepers, SimpleUtils, SkinsRestorer, SkQuery, Skript, Slimefun, SlimefunLuckyBlocks, SlimefunOreChunks, SlimeHUD, SlimyTreeTaps, spark, SpiritsUnchained, StreakRewards, SuperbVote, TAB, TinkerTools, TogglePvp, TokenManager, TradeSystem, TreasureChest, UltimateGenerators, Vault, Vehicles, VehiclesFlags, ViaBackwards, ViaVersion, VillagerUtil, VoidChest, Votifier, WG-GUI, Wildernether, WorldBorderAPI, WorldGuard, zAuctionHouse-Discord, zAuctionHouseV3

### Plugin Version

1.19.4-40.2

### Server Version

git-Purpur-1894 (MC: 1.19.3)*

**Comment by Wolfieheart** [comment]
2 Potential Souces could neither be:

- Bentobox
- Residence

Or could be entirely unrelated and be pointing at Lands as well which you dont use. But gonna investigate over the coming dats and see what I can find :)

**Comment by Wolfieheart** [comment]
Aha Culprit found and I found another issue along side this. Nice catches btw :D

**Comment by Wolfieheart** [comment]
Hey there this has now been fixed - If you want to test this, you can extract the dev version of this build from: https://github.com/Wolfieheart/ArmorStandEditor/actions/runs/4646315802 whenever the run has been complete. Please test it and let me know if it is still occuring
