### ISSUE TITLE
[Bug]: Commands not working correctly on Console

### ISSUE THREAD

**Issue by Wolfieheart** [Wolfieheart/ArmorStandEditor#284]
### Expected behavior

Commands should be able to run successfully from console using all Aliases - 

Hey, I got this error when I ran /armorstandeditor in console

### Observed/Actual behavior

[09:08:25 INFO]: /ase version
[09:08:25 INFO]: /ase help or /ase ?
[09:08:25 INFO]: /ase reload
[09:08:25 WARN]: Unexpected exception while parsing console command "armorstandeditor"
org.bukkit.command.CommandException: Unhandled exception executing command 'armorstandeditor' in plugin ArmorStandEditor v1.20.1-43
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1003) ~[paper-1.20.1.jar:git-Paper-57]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchServerCommand(CraftServer.java:966) ~[paper-1.20.1.jar:git-Paper-57]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:501) ~[paper-1.20.1.jar:git-Paper-57]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:448) ~[paper-1.20.1.jar:git-Paper-57]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-57]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-57]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-57]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.ClassCastException: class com.destroystokyo.paper.console.TerminalConsoleCommandSender cannot be cast to class org.bukkit.entity.Player (com.destroystokyo.paper.console.TerminalConsoleCommandSender and org.bukkit.entity.Player are in unnamed module of loader java.net.URLClassLoader @b7dd107)
        at io.github.rypofalem.armorstandeditor.CommandEx.onCommand(CommandEx.java:96) ~[armorstandeditor-1.20.1-43.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 9 more

### Steps/models to reproduce

N/A

### Plugin list

n/a

### Plugin Version

1.20.1-43 (Pre-Residence Removal)

### Server Version

1.20

**Comment by Wolfieheart** [comment]
NOTE this still exists in 1.20.1-43.2 and was not hotfixed down, this will be fixed in 1.20.1-44
