### ISSUE TITLE
[Bug]: Same error as #527 again

### ISSUE THREAD

**Issue by SeemWind** [Wolfieheart/ArmorStandEditor#529]
### Expected behavior

#527

### Observed/Actual behavior

```
Could not pass event PlayerInteractAtEntityEvent to ArmorStandEditor v1.20.6-46.2
java.lang.NoSuchFieldError: Class org.bukkit.inventory.ItemFlag does not have member field 'org.bukkit.inventory.ItemFlag HIDE_ADDITIONAL_TOOLTIP'
        at io.github.rypofalem.armorstandeditor.menu.PresetArmorPosesMenu.createIcon(PresetArmorPosesMenu.java:114) ~[armorstandeditor-1.20.6-46.2.jar:?]
        at io.github.rypofalem.armorstandeditor.menu.PresetArmorPosesMenu.fillInventory(PresetArmorPosesMenu.java:77) ~[armorstandeditor-1.20.6-46.2.jar:?]
        at io.github.rypofalem.armorstandeditor.menu.PresetArmorPosesMenu.openMenu(PresetArmorPosesMenu.java:129) ~[armorstandeditor-1.20.6-46.2.jar:?]
        at io.github.rypofalem.armorstandeditor.PlayerEditor.choosePreset(PlayerEditor.java:223) ~[armorstandeditor-1.20.6-46.2.jar:?]
        at io.github.rypofalem.armorstandeditor.PlayerEditor.editArmorStand(PlayerEditor.java:179) ~[armorstandeditor-1.20.6-46.2.jar:?]
        at io.github.rypofalem.armorstandeditor.PlayerEditor.reverseEditArmorStand(PlayerEditor.java:261) ~[armorstandeditor-1.20.6-46.2.jar:?]
        at io.github.rypofalem.armorstandeditor.PlayerEditorManager.applyRightTool(PlayerEditorManager.java:362) ~[armorstandeditor-1.20.6-46.2.jar:?]
        at io.github.rypofalem.armorstandeditor.PlayerEditorManager.onArmorStandInteract(PlayerEditorManager.java:128) ~[armorstandeditor-1.20.6-46.2.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:git-Folia-"ec6b172"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$3.performInteraction(ServerGamePacketListenerImpl.java:2795) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$3.a(ServerGamePacketListenerImpl.java:2848) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAtLocationAction.dispatch(ServerboundInteractPacket.java:159) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2784) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$2(PacketUtils.java:102) ~[?:?]
        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1646) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at java.lang.Thread.run(Thread.java:1570) ~[?:?]
```

### Steps/models to reproduce

same

### Plugin list

same

### Plugin Version

same

### Server Version

same

**Comment by Wolfieheart** [comment]
Fixed with https://github.com/Wolfieheart/ArmorStandEditor/commit/48450c39347c38a74061ec5db1c865a8ca6ed2f9
